MvcGolLig/Areas/YonetimPaneli/Controllers/FiyatTanimlamaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcGolLig.Models;

namespace MvcGolLig.Areas.YonetimPaneli.Controllers
{
    public class FiyatTanimlamaController : Controller
    {
        private vtGolLigEntities db = new vtGolLigEntities();

        // GET: YonetimPaneli/FiyatTanimlama
        public ActionResult Index(int saha=-1)
        {
            try
            {
                int id = int.Parse(Session["golliglogin"].ToString());
                sahaYukle(id);

                //giriş yapan kullanıcının yetkisi olan sahalar
                if (saha==-1)
                {
                    var sahalar = db.tblSahaKullanici.Where(c => c.panelKullanici == id).Select(c => c.saha);

                    var tblFiyat = db.tblFiyat.Where(x => sahalar.Contains(x.saha)).Include(t => t.tblRezervasyonSaatleri).Include(t => t.tblSaha);

                    return View(tblFiyat.ToList().OrderByDescending(c => c.saha));
                }
                else
                {
                    var sahalar = db.tblSahaKullanici.Where(c => c.panelKullanici == id && c.saha.Value==saha).Select(c => c.saha);

                    var tblFiyat = db.tblFiyat.Where(x => sahalar.Contains(x.saha)).Include(t => t.tblRezervasyonSaatleri).Include(t => t.tblSaha);

                    return View(tblFiyat.ToList().OrderByDescending(c => c.saha));
                }
            }
            catch (Exception)
            {
                return Redirect("/yonetimpaneli");
            }
             
        }
        void sahaYukle(int kulid)
        {
            var sahalar = db.tblSahaKullanici.Where(c => c.panelKullanici == kulid).Select(c => c.saha );

            var sahaList = db.tblSaha.Where(x => sahalar.Contains(x.sahaId)).ToList();


            List<SelectListItem> l = new List<SelectListItem>();
            foreach (var item in sahaList)
            {
                l.Add(new SelectListItem { Text = item.adi, Value = item.sahaId.ToString() });
            }

            ViewBag.SahaList = l;
        }

        [HttpPost]
        public JsonResult TumunuGuncelle(int saha=0, double fiyat = 0)
        {
            try
            {
                int kulid = int.Parse(Session["golliglogin"].ToString());

                tblSahaKullanici yetki = db.tblSahaKullanici.Where(d => d.panelKullanici == kulid && d.saha==saha).FirstOrDefault();
                if (yetki != null)
                {

                    foreach (var item in db.tblFiyat.Where(d=>d.saha==saha).ToList())
                    {
                        item.fiyat = fiyat;
                    }
                    db.SaveChanges();
                    return Json(new { basarili = true, text = "Fiyatlar güncellendi." });                    
                }
                else
                {
                    return Json(new { basarili = false, text = "Saha güncelleme yetkisine sahip değilsiniz." });
                }
            }
            catch (Exception)
            {
                return Json(new { basarili = false, text = "Fiyat güncelleme sırasında hata oluştu." });
            }
        }





        // GET: YonetimPaneli/FiyatTanimlama/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFiyat tblFiyat = db.tblFiyat.Find(id);
            if (tblFiyat == null)
            {
                return HttpNotFound();
            }
            ViewBag.rezSaati = new SelectList(db.tblRezervasyonSaatleri, "rezId", "aciklama", tblFiyat.rezSaati);
            ViewBag.saha = new SelectList(db.tblSaha, "sahaId", "adi", tblFiyat.saha);
            return View(tblFiyat);
        }
         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "fiyatId,saha,rezSaati,fiyat")] tblFiyat tblFiyat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblFiyat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.rezSaati = new SelectList(db.tblRezervasyonSaatleri, "rezId", "aciklama", tblFiyat.rezSaati);
            ViewBag.saha = new SelectList(db.tblSaha, "sahaId", "adi", tblFiyat.saha);
            return View(tblFiyat);
        }

        [HttpPost]
        public JsonResult fiyatguncelle(int id,int yeniFiyat)
        {
            try
            {
                var fiyat= db.tblFiyat.Where(x => x.fiyatId == id).FirstOrDefault();
                if (fiyat!=null)
                {
                    fiyat.fiyat = yeniFiyat;
                    db.Entry(fiyat).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            } 
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcGolLig/Areas/YonetimPaneli/Controllers/HomeController.cs
using MvcGolLig.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace MvcGolLig.Areas.YonetimPaneli.Controllers
{
    public class HomeController : Controller
    {
        vtGolLigEntities vt = new vtGolLigEntities();
        // GET: YonetimPaneli/Home
        public ActionResult Index(int id = 0, string tarih = "")
        { 
            
            sayilariYaz();
            ViewBag.bugun = DateTime.Now.ToString("dd.MM.yyyy");

            try
            {
                if (tarih!="")
                {
                    sahaRezRapor(int.Parse(Session["golliglogin"].ToString()), tarih);
                    ViewBag.tarihgirisi = tarih;
                }
                else
                {
                    sahaRezRapor(int.Parse(Session["golliglogin"].ToString()), DateTime.Now.ToString("dd.MM.yyyy"));
                }
                
            }
            catch (Exception)
            {
                Redirect("/");
            }

            ViewBag.takim = new SelectList(vt.tblKullanici.Where(x=>x.aktif==1), "telefonNo", "adSoyad");
            return View();
        }

        void sahaRezRapor(int id=0,string tarih="")
        {
            try
            {
                if (id==0)
                {
                    id= int.Parse(Session["golliglogin"].ToString()); 
                }
                if (tarih=="")
                {
                    tarih = DateTime.Now.ToString("dd.MM.yyyy");
                }
            }
            catch (Exception)
            {
                Redirect("/");
            }
            var sConnection = ((SqlConnection)vt.Database.Connection);

           
            if (sConnection != null && sConnection.State == ConnectionState.Closed)
            {
                sConnection.Open();
            }
            List<Rapor> raporList = new List<Rapor>();
            DateTime tarihBas = DateTime.Now;
            try
            {
                tarihBas = DateTime.Parse(tarih);
            }
            catch (Exception)
            { }

            using (SqlDataAdapter ad = new SqlDataAdapter())
            {
                //SqlDataAdapter com = new SqlDataAdapter("exec sp_sahaRezRapor " + id + ", '" + tarih + "' ", sConnection);
                //com.Fill(dt);

                var sahalar=vt.tblSahaKullanici.Where(x => x.panelKullanici == id).ToList().OrderBy(x=>x.tblSaha.adi);

                foreach (var item in sahalar.ToList())
                {
                    Rapor r = new Rapor();
                    r.SahaAdi = item.tblSaha.adi;

                    DataTable dt = new DataTable();
                    SqlDataAdapter com = new SqlDataAdapter("exec sp_SonRezervasyonlar '"+item.saha+"','"+tarihBas.ToShortDateString()+"' "+
                        ",'"+tarihBas.AddDays(1).ToShortDateString()+"' "+
                        ",'" + tarihBas.AddDays(2).ToShortDateString() + "' "+
                        ",'" + tarihBas.AddDays(3).ToShortDateString() + "', "+
                        "'" + tarihBas.AddDays(4).ToShortDateString() + "' "+
                        ",'" + tarihBas.AddDays(5).ToShortDateString() + "' "+
                        ",'" + tarihBas.AddDays(6).ToShortDateString() + "'  ", sConnection);

                    com.Fill(dt);

                    r.Rezler = dt;
                    raporList.Add(r);
                }

                
            }
            sConnection.Close();

            ViewBag.Rezler = raporList;
        }

        void sayilariYaz()
        {
            var saha = vt.vw_publicsaha.ToList();
            var takim = vt.vw_publictakim.ToList();
            var mac = vt.vw_publicmac.ToList();
            var kullanici = vt.publickullanici.ToList();


            ViewBag.KayitliSaha = saha.Count();
            ViewBag.KayitliTakim = takim.Count();
            ViewBag.KayitliMac = mac.Count();
            ViewBag.KayitliKullanici = kullanici.Count();


            ViewBag.publicsaha = saha;
            ViewBag.publictakim = takim;
            ViewBag.publickullanici = kullanici;
            ViewBag.publicmac = mac.OrderByDescending(x=>x.tarih) ;
        }

        public ActionResult cikis()
        {
            Session.Abandon();
            return RedirectToAction("Index");// Redirect("/");
        }

        [HttpPost]
        public JsonResult rezervasyonYap(int sahaId,string takim,string tarih,string takimTel,string saat,double fiyat,int fiyatId)
        {
            try
            {
                if (takimTel!=null)
                {
                    takimTel = takimTel.Replace("(", "");
                    takimTel = takimTel.Replace(")", "");
                    takimTel = takimTel.Replace("-", "");
                    takimTel = takimTel.Replace(" ", "");
                }
                DateTime dt = DateTime.Parse(tarih);
                var kul=vt.tblKullanici.Where(x => x.telefonNo == takimTel).FirstOrDefault();
                var tFiyat = vt.tblFiyat.Where(x => x.fiyatId == fiyatId).FirstOrDefault();

                tblRezervasyon rez = new tblRezervasyon();
                rez.saha = sahaId;
                rez.tarih = dt;
                rez.durum = 1;

                if (kul!=null)
                {
                    rez.tblKullanici = kul;
                    rez.takim = kul.kullaniciId;
                }
                else
                {
                    rez.aciklama = takim + " " + takimTel;
                }
                if (tFiyat != null)
                {
                    rez.fiyat = fiyat;
                    rez.rezSaati = tFiyat.rezSaati;
                    rez.tblFiyat = tFiyat;
                }
                else
                {
                    return Json(new { basarili = false, text = "Rezervasyon oluşturma sırasında hata oluştu.Fiyat bilgilerine erişilemedi." });
                }

                vt.tblRezervasyon.Add(rez);
                vt.SaveChanges();

                return Json(new { basarili = true, text = "Rezervasyon işlemi yapıldı." });
            }
            catch (Exception)
            {
                return Json(new { basarili = false, text = "Rezervasyon oluşturma sırasında hata oluştu." });
            }
        }

        [HttpPost]
        public JsonResult DurumDegistir(int id, int durum = 1)
        {
            try
            {
                tblRezervasyon rez = vt.tblRezervasyon.Where(d => d.rezId == id).FirstOrDefault();
                int userid = int.Parse(Session["golliglogin"].ToString());
                var yetki = vt.tblSahaKullanici.Where(x => x.saha == rez.saha && x.panelKullanici == userid).FirstOrDefault();
                if (yetki == null)
                {
                    return Json(new { basarili = false, text = "Bu rezervasyonu güncelleme yetkiniz yok." });
                }

                if (rez != null)
                {
                    rez.durum = durum;
                    vt.SaveChanges();
                    var x = rez.tblKullanici;
                    if (durum == 1)
                    { 
                        rezervasyonSahibineMailGonder(durum, x, rez); 
                        return Json(new { basarili = true, text = "Rezervasyon onaylandı." }); 
                    }
                    else
                    {
                        rezervasyonSahibineMailGonder(durum, x, rez);
                        return Json(new { basarili = true, text = "Rezervasyon iptal edildi." });
                    }
                }
                else
                {
                    return Json(new { basarili = false, text = "Rezervasyon güncelleme sırasında hata oluştu." });
                }
            }
            catch (Exception)
            {
                return Json(new { basarili = false, text = "Rezervasyon güncelleme sırasında hata oluştu." });
            }
        }

        private void rezervasyonSahibineMailGonder(int durum, tblKullanici x, tblRezervasyon rez)
        {
            try
            {
                //var x = vt.tblKullanici.Where(z => z.telefonNo == telefon).FirstOrDefault();
                //var x = db.tblSiteBilgileri.FirstOrDefault();
                if (x != null)
                {
                    var body = "";
                    var message = new MailMessage();
                    message.To.Add(new MailAddress(x.yetkiliMail));
                    message.From = new MailAddress("info@gollig.com");
                    if (durum == 1)
                    {
                        body = "<p>Merhaba " + x.adSoyad + ",</p><p>" + rez.tblSaha.adi + " isimli halı sahasına yaptığın " + rez.tarih.Value.ToString("dd.MM.yyyy") + " " + rez.tblRezervasyonSaatleri.aciklama + " tarihli rezervasyonun onaylanmıştır.</p>" +
                       "<p>www.gollig.com</p>";
                        message.Subject = "GolLig | Rezervasyonun Onaylandı!";
                    }
                    else
                    {
                        body = "<p>Merhaba " + x.adSoyad + ",</p><p>" + rez.tblSaha.adi + " isimli halı sahasına yaptığın " + rez.tarih.Value.ToString("dd.MM.yyyy") + " " + rez.tblRezervasyonSaatleri.aciklama + " tarihli rezervasyonun iptal edilmiştir." +
                            " </p>" +
                       "<p>www.gollig.com</p>";
                        message.Subject = "GolLig | Rezervasyonun Onaylanmadı!";
                    }


                    message.Body = (body);
                    message.IsBodyHtml = true;

                    NetworkCredential netCred = new NetworkCredential("info@gollig.com", "GolLig2016");

                    SmtpClient smtpobj = new SmtpClient("gollig.com");
                    smtpobj.EnableSsl = false;
                    smtpobj.Credentials = netCred;
                    message.IsBodyHtml = true;

MvcGolLig/Areas/YonetimPaneli/Controllers/MenuController.cs
using MvcGolLig.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcGolLig.Areas.YonetimPaneli.Controllers
{
    public class MenuController : Controller
    {
        vtGolLigEntities vt = new vtGolLigEntities();
        // GET: YonetimPaneli/Menu
        public ActionResult Index()
        {
            try
            {
                if (Session["golliglogin"] != null)
                {
                    ViewBag.Normal = vt.tblMenu.Where(x => x.kullaniciTipi == 100).ToList();

                    int tip = int.Parse(Session["golliglogintip"].ToString());
                    if (tip==100)
                    { 

                        return PartialView(vt.tblMenu.Where(x => x.kullaniciTipi == tip).ToList());
                    }
                    else
                    {
                        ViewBag.Admin = vt.tblMenu.Where(x => x.kullaniciTipi == 0).ToList();
                        return PartialView(vt.tblMenu.ToList());
                    }
                }
                else
                {
                    return Redirect("/giris");
                }
            }
            catch (Exception)
            {
                return Redirect("/giris");
            }
             
        }
    }
}

MvcGolLig/Areas/YonetimPaneli/Views/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>GolLig Yönetim Paneli</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        @*<meta name="viewport" content="width=device-width, initial-scale=1">*@

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">



        <meta name="description" content="">
        <meta name="author" content="">
          
        <link href="~/Areas/YonetimPaneli/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Areas/YonetimPaneli/css/sb-admin.css" rel="stylesheet" />
        <link href="~/Areas/YonetimPaneli/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/> 
       


        <script src="~/Areas/YonetimPaneli/js/jquery.js"></script> 
        <script src="~/Areas/YonetimPaneli/js/bootstrap.min.js"></script>

        <link rel="shortcut icon" type="image/png" href="~/images/logo.ico" />

        @RenderSection("head", required: false)
    </head>
   
<body>
      
        <div id="wrapper"> 
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/yonetimpaneli">Gol Lig Yönetici Paneli</a>
                </div>
                <!-- Top Menu Items -->
                <ul class="nav navbar-right top-nav">

                    @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                        <ul class="dropdown-menu alert-dropdown">
                            <li>
                                <a href="#">Bildirim 1  </a>
                            </li>
                            <li>
                                <a href="#">Bildirim 2  </a>
                            </li>
                            <li>
                                <a href="#">Bildirim 3  </a>
                            </li>
                            <li>
                                <a href="#">Bildirim 4  </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">View All</a>
                            </li>
                        </ul>
                    </li>*@
                    <li class="dropdown">
                       @* <asp:LinkButton ID="btnCikis" runat="server" OnClick="btnCikis_Click">Çıkış Yap</asp:LinkButton>*@
                        <a onclick="cikisyap()" style="cursor:pointer">Çıkış Yap</a>
                    </li>
                </ul>
                <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <div class="nav navbar-nav side-nav">
                        <div class="list-group">
                            @*@Html.Partial("~/Areas/YonetimPaneli/Views/Menu/Index.cshtml")*@
                            @try
                            {
                                if (Session["golliglogin"] != null)
                                {
                                    { Html.RenderAction("Index", "Menu"); }
                                }
                                else { Response.Redirect("/giris"); }
                            }
                            catch (Exception)
                            {
                                Response.Redirect("/");
                            }
                        </div>
                    </div>
                </div>



                <!-- /.navbar-collapse -->
            </nav>

            @RenderBody()

             
        </div>

    <script>
        function cikisyap() {
            $.post("/home/cikis", function (data, status) {
                window.location = "/";
            });
        }
    </script>
     
</body>    
</html>