MvcGolLig/Controllers/GirisController.cs
using MvcGolLig.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcGolLig.Controllers
{
    public class GirisController : Controller
    {
        // GET: Giris
        vtGolLigEntities vt = new vtGolLigEntities();

        public ActionResult Index(string txtGirisTelefon, string txtGirisSifre)
        {
            sehirleriYukle();
            takimDurumlariYukle();
            IlcerleriGetir(0);
            if (txtGirisTelefon!=null)
            {
                txtGirisTelefon = txtGirisTelefon.Replace("(", "");
                txtGirisTelefon = txtGirisTelefon.Replace(")", "");
                txtGirisTelefon = txtGirisTelefon.Replace("-", "");
                txtGirisTelefon = txtGirisTelefon.Replace(" ", "");
            }

            try
            {
                if (Session["golliglogin"]!=null)
                {
                    return Redirect("/");
                }
            }
            catch (Exception)
            { 
            }

            if (txtGirisTelefon==null || txtGirisSifre==null)
            {
                return View();
            }
            
                var k = vt.tblKullanici.Where(x => x.telefonNo==txtGirisTelefon && x.sifre == txtGirisSifre && x.aktif == 1).FirstOrDefault();
                if (k != null)
                {
                    Session.Add("golliglogin", k.kullaniciId);
                    if (k.admin == 1)
                    {
                        Session.Add("golliglogintip", "0");
                    }
                    else
                    {
                        Session.Add("golliglogintip", "100");
                    }

                        try
                        {
                            return RedirectToAction("index", "sahadetay", new { sahaAdi = Session["back"],Tarih=Session["backtarih"],kod=Session["backkod"] });
                        }
                        catch (Exception)
                        { return Redirect("/"); }                     
                }                
            
            return View();           
            
        }

        private void takimDurumlariYukle()
        {
            List<SelectListItem> takimDurumList = new List<SelectListItem>();
            //takimDurumList.Add(new SelectListItem { Text = "Hepsi", Value = "-1" });
            foreach (var item in vt.tblTakimDurumu.ToList())
            {
                takimDurumList.Add(new SelectListItem { Text = item.aciklama, Value = item.takimDurumuId.ToString() });
            }
            ViewBag.TakimDurumlari = takimDurumList;
        }
        void sehirleriYukle()
        {
            List<SelectListItem> sehirList = new List<SelectListItem>();
            //sehirList.Add(new SelectListItem { Text = "Hepsi", Value = "-1" });
            foreach (var item in vt.iller.ToList())
            {
                sehirList.Add(new SelectListItem { Text = item.sehir, Value = item.id.ToString() });
            }
            ViewBag.Sehirler = sehirList;
        }

        public ActionResult IlcerleriGetir(int id = 0)
        {
            List<SelectListItem> l = new List<SelectListItem>();
            l.Add(new SelectListItem { Text = "Hepsi", Value = "-1" });
            foreach (var item in vt.ilceler.Where(x => x.sehir == id).ToList())
            {
                l.Add(new SelectListItem { Text = item.ilce, Value = item.id.ToString() });
            } 
            ViewBag.Ilceler = l;
            return View();
        }






        public ActionResult Kayit(string adSoyad,string sifre,string sifre2,string telefonNo,string mailadresi,string takimAdi,
            string aciklama,string TakimDurumlari, string Sehirler,string Ilceler,string listedeGorunsun,
            HttpPostedFileBase resim)
        {
            sehirleriYukle();
            takimDurumlariYukle();
            IlcerleriGetir(0);
            telefonNo = telefonNo.Replace("(", "");
            telefonNo = telefonNo.Replace(")", "");
            telefonNo = telefonNo.Replace("-", "");
            telefonNo = telefonNo.Replace(" ", "");

            Helpers.CaptchaHelper captha = new Helpers.CaptchaHelper(HttpContext);
            if (captha.Validate())
            {
                if (listedeGorunsun==null)
                {
                    listedeGorunsun = "0";
                }
                bool resmiKaydet = false;
                if (resim != null)
                {
                    if (resim.ContentLength > 0)
                    {
                        double bayt = resim.ContentLength;
                        double mbBirim = 1048576;
                        double megabayt = bayt / mbBirim;
                        if (megabayt>3)
                        {
                            ViewBag.StartupScript = "alert('Takım resmi (max) 3mb olmalıdır!');";
                        }
                        else
                        {
                            resmiKaydet = true;
                        }
                    }
                }

                var kontrol = vt.tblKullanici.Where(b => b.telefonNo == telefonNo).FirstOrDefault();
                if (kontrol!=null)
                {
                    ViewBag.StartupScript = "alert('Bu telefon numarası başka bir hesaba tanımmlı.');";
                    return View("Index");
                }
                

                tblKullanici t = new tblKullanici();
                t.adSoyad = adSoyad;
                t.sifre = sifre;
                t.telefonNo = telefonNo;
                t.aktif = 1;
                t.admin = 0;
                t.yetkiliMail = mailadresi;
               // t.takimAdi = takimAdi;
                //t.takimYetkilisi = yetkiliAdi;
               // t.yetkiliTelNo = yetkiliTelNo;
                //t.takimAciklama = aciklama;
                //t.takimDurumu = int.Parse(TakimDurumlari);
                //t.il = int.Parse(Sehirler);
                //t.ilce = int.Parse(Ilceler);
                //t.gorunsunMu = listedeGorunsun.Contains("on") ? 1 : 0;
                if (!resmiKaydet)
                {
                    t.takimLogo = "noimage.png";
                }

                var takim= vt.tblKullanici.Add(t);
                vt.SaveChanges();

                if (resmiKaydet)
                {
                    string dosyaAdi = takim.kullaniciId.ToString();
                    string filePath = Path.Combine(Server.MapPath("~/img"), dosyaAdi + Path.GetExtension(resim.FileName));
                    resim.SaveAs(filePath);

                    vt.tblKullanici.Attach(takim);
                    var entry = vt.Entry(takim);
                    takim.takimLogo = dosyaAdi + Path.GetExtension(resim.FileName);
                    entry.Property(e => e.takimLogo).IsModified = true;
                     
                    vt.SaveChanges();
                } 


                ViewBag.StartupScript = "alert('Üyelik işleminiz tamamlandı.');";
                Session["golliglogin"] = takim.kullaniciId;
                Session.Add("golliglogintip", "100");

                mailGonder(adSoyad, mailadresi);

                try
                {
                    return RedirectToAction("index", "sahadetay", new { sahaAdi = Session["back"], Tarih = Session["backtarih"], kod = Session["backkod"] });
                }
                catch (Exception)
                { return Redirect("/"); }

                //return Redirect("/");
            }
            else
            {
                ViewBag.StartupScript = "alert('Doğrulama işlemi başarısız!');";
            }
             
            return View("Index");
        }

        private void mailGonder(string adSoyad, string mailadresi)
        {
            try
            { 
                var x = vt.tblSiteBilgileri.FirstOrDefault();
                if (x != null)
                {
                    var body = "";
                    var message = new MailMessage();
                    message.To.Add(new MailAddress(x.mail));
                    message.From = new MailAddress("info@gollig.com");
                      
                        body = "<p>Merhaba, " + adSoyad + " ismi ile yeni bir kullanıcımız var.</p><p>Mail Adresi: " + mailadresi +  "</p><p>www.gollig.com</p>";
                        message.Subject = "GolLig | Yeni Bir Üye!";
                    


                    message.Body = (body);
                    message.IsBodyHtml = true;

                    NetworkCredential netCred = new NetworkCredential("info@gollig.com", "GolLig2016");

                    SmtpClient smtpobj = new SmtpClient("gollig.com");
                    smtpobj.EnableSsl = false;
                    smtpobj.Credentials = netCred;
                    message.IsBodyHtml = true;


                    smtpobj.Send(message);

                    // return Json(new { basarili = true, text = "Şifreniz mail adresinize gönderildi." });
                } 
            }
            catch (Exception ex)
            {
                //return Json(new { basarili = false, text = "İşlem gerçekleşirken beklenmedik bir hata oluştu.Lütfen tekrar deneyin." });
            }
        }

        [HttpPost]
        public JsonResult sifremiunuttum(string telefon)
        {
            try
            { 
                var x = vt.tblKullanici.Where(z => z.telefonNo == telefon).FirstOrDefault();
                if (x != null)
                {
                    var body = "<p>Şifreniz: " + x.sifre + " </p><p>www.gollig.com</p>";
                    var message = new MailMessage();
                    message.To.Add(new MailAddress(x.yetkiliMail));
                    message.From = new MailAddress("info@gollig.com");
                    message.Subject = "GolLig | Şifremi Unuttum";
                    message.Body = (body);

MvcGolLig/Views/Giris/IlcerleriGetir.cshtml
@{
    ViewBag.Title = "IlcerleriGetir";
    //Layout = "~/Views/_Layout.cshtml";

    <!-- Animate.css -->
    <link href="~/css/animate.css" rel="stylesheet" />
    <!-- Icomoon Icon Fonts-->
    <link href="~/css/icomoon.css" rel="stylesheet" />
    <!-- Bootstrap  -->
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <!-- Superfish -->
    <link href="~/css/superfish.css" rel="stylesheet" />
    <!-- Magnific Popup -->
    <link href="~/css/magnific-popup.css" rel="stylesheet" />
    <!-- Date Picker -->
    <link href="~/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <!-- CS Select -->
    <link href="~/css/cs-select.css" rel="stylesheet" />
    <link href="~/css/cs-skin-border.css" rel="stylesheet" />


    <link href="~/css/style.css" rel="stylesheet" />
}


@Html.DropDownList("Ilceler", (List<SelectListItem>)ViewBag.ilceler, new { @class = "form-control" } )

MvcGolLig/Views/Giris/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
    
}


<script src="~/jsValidate/jquery.min.js"></script>
<script src="~/jsValidate/jquery.validate.min.js"></script>
<script src="~/jsValidate/form-validation.js"></script>

<script src="~/js/jquery.maskedinput.js" type="text/javascript"></script>

<style>
   label.error {
  color: red;
  position:absolute;
      right: 0px;
    padding-right: 15px;
}

</style>

<div id="fh5co-tours" class="fh5co-section-gray" style="background-image: url(images/cover_bg_1.jpg);">
    <div class="container">
        <div class="row">


            <div class="tabulation2 animate-box" style="width:100%;opacity:1">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#flights" aria-controls="flights" role="tab" data-toggle="tab">Giriş Yap</a>
                    </li>

                    <li role="presentation">
                        <a href="#register" aria-controls="register" role="tab" data-toggle="tab">Kayıt Ol</a>
                    </li>
                    <li role="presentation">
                        <a href="#sifremiunuttum" aria-controls="sifremiunuttum" role="tab" data-toggle="tab">Şifremi Unuttum</a>
                    </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="flights">
                        <div class="row">
                    @using (Html.BeginForm())
                    {
                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="input-field">
                                    <label for="from">Telefon No</label>
                                    <input type="text" class="form-control" name="txtGirisTelefon" id="txtGirisTelefon" placeholder="" />
                                </div>
                            </div>
                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="input-field">
                                    <label for="from">Şifre</label>
                                    <input type="password" class="form-control" name="txtGirisSifre" id="from-place" placeholder="" />
                                </div>
                            </div>


                            <div class="col-xs-12">
                                <input type="submit" class="btn btn-primary btn-block" type="submit" value="Giriş Yap">
                            </div>
}
                        </div>
                    </div>

                    <div role="tabpanel" class="tab-pane" id="register">
                        @{Html.RenderPartial("Kayit"); }
                    </div>


                    <div role="tabpanel" class="tab-pane" id="sifremiunuttum">
                        <div class="row">
                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="input-field">
                                    <label for="from">Telefon No</label>
                                    <input type="text" class="form-control" name="txtSifremiUnuttum" id="txtSifremiUnuttum" placeholder="" />
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <input type="submit" class="btn btn-primary btn-block" onclick="sifremiunuttum()" value="Gönder">
                            </div>

                        </div>
                     </div>
                </div>
            </div>






        </div>





    </div>
</div>

<script>
    jQuery(function ($) {
        $("#txtGirisTelefon").mask("(999) 999-9999", { placeholder: "" });
    });
</script>


<script type="text/javascript">
    function sifremiunuttum() {

        var ptelefon= $("#txtSifremiUnuttum").val();
        if (ptelefon == "") {
            alert('Telefon numaranızı giriniz.');
            return false;
        }
        //Posting them to server with ajax
        $.ajax({
            url: '/giris/sifremiunuttum',
            type: 'POST',
            data: { telefon: ptelefon },
            success: function (data) {
                if (data.basarili==true) {
                    alert(data.text);
                    window.location = '/';
                }
                else {
                    alert(data.text);
                }
            },
            error: function (hata, ajaxOptions, thrownError) {
                alert('Beklenmedik bir hata oluştu lütfen tekrar deneyin.');
            }
        });
    }
</script>


<script type="text/javascript" defer="defer">
    @Html.Raw(ViewBag.StartupScript)
</script>


<script type="text/javascript">
    $(function () {
        
            $('#Sehirler').change(function () {
                $.get('/Giris/IlcerleriGetir/?id=' + $(this).val(), function (data) {
                    $('.ilceler').html(data);
                });
            });
        });

</script>

MvcGolLig/Views/Giris/Kayit.cshtml
<script src="~/js/jquery-1.10.2.min.js"></script>
<link href="~/js/jquery-ui.css" rel="stylesheet" /> 
<script src="~/jsValidate/jquery.min.js"></script>
<script src="~/jsValidate/jquery.validate.min.js"></script>
<script src="~/jsValidate/form-validation.js"></script>
 

<script src="~/js/jquery.maskedinput.js" type="text/javascript"></script>

<div class="row">
    @using (Html.BeginForm("Kayit", "Giris", FormMethod.Post, new { name = "registration", enctype = "multipart/form-data" }))
    {
        <div class="col-xxs-12 col-xs-6 mt">
            <div class="input-field">
                <label for="adSoyad">Ad Soyad</label>
                @Html.TextBox("adSoyad", "",
                         new
                         {
                             @class = "form-control",
                             @type = "text",
                             @name = "adSoyad",
                         })
            </div>
        </div>
                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="input-field">
                                    <label for="from">Şifre</label>
                                    @Html.TextBox("Sifre", "",
                                    new
                                    {
                                        @class = "form-control",
                                        @type = "password",
                                        @name = "Sifre",
                                    })
                                </div>
                            </div>
                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="input-field">
                                    <label for="from">Şifre Tekrar</label>
                                    @Html.TextBox("Sifre2", "",
                                    new
                                    {
                                        @class = "form-control",
                                        @type = "password",
                                        @name = "sifre2",
                                    })
                                </div>
                            </div>
                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="input-field">
                                    <label for="from">Telefon No</label>
                                     
                                    <input placeholder="Giriş Yaparken kullanılacak" type="text" name="telefonNo" id="telefonNo" class="form-control" >  
                                </div>
                            </div>
                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="input-field">
                                    <label for="from">Mail</label>
                                    
                                    <input name="mailadresi" id="mailadresi" class="form-control" placeholder = "info@gollig.com"
                                           style="text-transform:none" />
                                </div>
                            </div>


                            <div class="col-xxs-12 col-xs-6 mt">
                                <div class="g-recaptcha" data-sitekey="6LetuhAUAAAAAPTWlUM2mM2U4aaiYeFHyVR6qsNO"></div>
                                <script src='https://www.google.com/recaptcha/api.js'></script>
                            </div>

                            <div class="col-xs-12">
                                <input type="submit" class="btn btn-primary btn-block" value="Kayıt Ol">
                            </div>
    }
</div>



<script>
    jQuery(function ($) {
        $("#telefonNo").mask("(999) 999-9999", { placeholder: "" });
    });
</script>

<script type="text/javascript">

    $(function () {
         

            $('#Sehirler').change(function () {
                $.get('/Giris/IlcerleriGetir/?id=' + $(this).val(), function (data) {
                    $('.ilceler').html(data);
                });
            });
        });

</script>