MvcGolLig/Areas/YonetimPaneli/Controllers/FiyatTanimlamaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcGolLig.Models;

namespace MvcGolLig.Areas.YonetimPaneli.Controllers
{
    public class FiyatTanimlamaController : Controller
    {
        private vtGolLigEntities db = new vtGolLigEntities();

        // GET: YonetimPaneli/FiyatTanimlama
        public ActionResult Index(int saha=-1)
        {
            try
            {
                int id = int.Parse(Session["golliglogin"].ToString());
                sahaYukle(id);

                //giriş yapan kullanıcının yetkisi olan sahalar
                if (saha==-1)
                {
                    var sahalar = db.tblSahaKullanici.Where(c => c.panelKullanici == id).Select(c => c.saha);

                    var tblFiyat = db.tblFiyat.Where(x => sahalar.Contains(x.saha)).Include(t => t.tblRezervasyonSaatleri).Include(t => t.tblSaha);

                    return View(tblFiyat.ToList().OrderByDescending(c => c.saha));
                }
                else
                {
                    var sahalar = db.tblSahaKullanici.Where(c => c.panelKullanici == id && c.saha.Value==saha).Select(c => c.saha);

                    var tblFiyat = db.tblFiyat.Where(x => sahalar.Contains(x.saha)).Include(t => t.tblRezervasyonSaatleri).Include(t => t.tblSaha);

                    return View(tblFiyat.ToList().OrderByDescending(c => c.saha));
                }
            }
            catch (Exception)
            {
                return Redirect("/yonetimpaneli");
            }
             
        }
        void sahaYukle(int kulid)
        {
            var sahalar = db.tblSahaKullanici.Where(c => c.panelKullanici == kulid).Select(c => c.saha );

            var sahaList = db.tblSaha.Where(x => sahalar.Contains(x.sahaId)).ToList();


            List<SelectListItem> l = new List<SelectListItem>();
            foreach (var item in sahaList)
            {
                l.Add(new SelectListItem { Text = item.adi, Value = item.sahaId.ToString() });
            }

            ViewBag.SahaList = l;
        }

        [HttpPost]
        public JsonResult TumunuGuncelle(int saha=0, double fiyat = 0)
        {
            try
            {
                int kulid = int.Parse(Session["golliglogin"].ToString());

                tblSahaKullanici yetki = db.tblSahaKullanici.Where(d => d.panelKullanici == kulid && d.saha==saha).FirstOrDefault();
                if (yetki != null)
                {

                    foreach (var item in db.tblFiyat.Where(d=>d.saha==saha).ToList())
                    {
                        item.fiyat = fiyat;
                    }
                    db.SaveChanges();
                    return Json(new { basarili = true, text = "Fiyatlar güncellendi." });                    
                }
                else
                {
                    return Json(new { basarili = false, text = "Saha güncelleme yetkisine sahip değilsiniz." });
                }
            }
            catch (Exception)
            {
                return Json(new { basarili = false, text = "Fiyat güncelleme sırasında hata oluştu." });
            }
        }





        // GET: YonetimPaneli/FiyatTanimlama/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFiyat tblFiyat = db.tblFiyat.Find(id);
            if (tblFiyat == null)
            {
                return HttpNotFound();
            }
            ViewBag.rezSaati = new SelectList(db.tblRezervasyonSaatleri, "rezId", "aciklama", tblFiyat.rezSaati);
            ViewBag.saha = new SelectList(db.tblSaha, "sahaId", "adi", tblFiyat.saha);
            return View(tblFiyat);
        }
         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "fiyatId,saha,rezSaati,fiyat")] tblFiyat tblFiyat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblFiyat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.rezSaati = new SelectList(db.tblRezervasyonSaatleri, "rezId", "aciklama", tblFiyat.rezSaati);
            ViewBag.saha = new SelectList(db.tblSaha, "sahaId", "adi", tblFiyat.saha);
            return View(tblFiyat);
        }

        [HttpPost]
        public JsonResult fiyatguncelle(int id,int yeniFiyat)
        {
            try
            {
                var fiyat= db.tblFiyat.Where(x => x.fiyatId == id).FirstOrDefault();
                if (fiyat!=null)
                {
                    fiyat.fiyat = yeniFiyat;
                    db.Entry(fiyat).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            } 
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcGolLig/Areas/YonetimPaneli/Views/FiyatTanimlama/Create.cshtml
@model MvcGolLig.Models.tblFiyat

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/YonetimPaneli/Views/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblFiyat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.saha, "saha", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("saha", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.saha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rezSaati, "rezSaati", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("rezSaati", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.rezSaati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcGolLig/Areas/YonetimPaneli/Views/FiyatTanimlama/Delete.cshtml
@model MvcGolLig.Models.tblFiyat

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/YonetimPaneli/Views/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblFiyat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblRezervasyonSaatleri.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblRezervasyonSaatleri.aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSaha.adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSaha.adi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcGolLig/Areas/YonetimPaneli/Views/FiyatTanimlama/Details.cshtml
@model MvcGolLig.Models.tblFiyat

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/YonetimPaneli/Views/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblFiyat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblRezervasyonSaatleri.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblRezervasyonSaatleri.aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSaha.adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSaha.adi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.fiyatId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcGolLig/Areas/YonetimPaneli/Views/FiyatTanimlama/Edit.cshtml
@model MvcGolLig.Models.tblFiyat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/YonetimPaneli/Views/_LayoutAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row" style="margin-right:0px">

            <h2>Fiyat Düzenle</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.fiyatId)

                    <div class="form-group">
                        <label class="control-label col-md-2">Saha</label> 
                        <div class="col-md-10">
                            <fieldset disabled>
                                @Html.DropDownList("saha", null, htmlAttributes: new { @class = "form-control" })
                                </fieldset>
                            @Html.HiddenFor(model => model.saha)

                                @Html.ValidationMessageFor(model => model.saha, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Saat</label> 
                        <div class="col-md-10">
                            <fieldset disabled>
                                @Html.DropDownList("rezSaati", null, htmlAttributes: new { @class = "form-control", @id = "disabledSelect" })
                            </fieldset>
                            @Html.HiddenFor(model => model.rezSaati)

                            @Html.ValidationMessageFor(model => model.rezSaati, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Fiyat</label> 
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.fiyat, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fiyat, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Kaydet" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Listeye Dön", "Index")
            </div>
        </div>

    </div>

</div>

MvcGolLig/Areas/YonetimPaneli/Views/FiyatTanimlama/Index.cshtml
@model IEnumerable<MvcGolLig.Models.tblFiyat>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/YonetimPaneli/Views/_LayoutAdmin.cshtml";
}

<script src="~/Areas/YonetimPaneli/sweetalert/sweetalert-dev.js"></script>
<link href="~/Areas/YonetimPaneli/sweetalert/sweetalert.css" rel="stylesheet" />

<style>
    .sweet-alert h2 {
        font-size: large;
    }
    .sweet-alert button {
        padding: 10px 15px;
    }
</style>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row" style="margin-right:0px">

            <h2>Fiyatlar</h2>
            <p>

                @using (Html.BeginForm("Index", "FiyatTanimlama",FormMethod.Get,new { @id="frmindex" } ))
                {
                    <div class="form-horizontal">
                        <div class="col-xs-6">
                            @Html.DropDownList("saha", new SelectList(ViewBag.SahaList, "Value", "Text"), new { @class = "form-control", id = "sahaselect" })
                        </div>

                        <div class="col-xs-3">
                            <input type="submit" value="Göster" class="btn btn-default" style="opacity:0"/>
                        </div>
                    </div>
                         
                             
                            <div class="form-horizontal">
                                <div class="col-xs-6 col-md-4">
                                    <input type="number" class="form-control" id="txtTumFiyat" placeholder="Fiyat">
                                </div>

                                <div class="col-xs-12 col-sm-6 col-md-8">
                                    <button type="button" onclick="tumunuguncelle();" class="btn btn-default">Tüm Fiyatları Güncelle</button>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                
                            </div>

                            }

</p>
        </div>

<br /><br />
            
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tr>
                                        <th>
                                            Saha
                                        </th>
                                        <th>
                                            Saat
                                        </th>
                                        <th>
                                            Fiyat
                                        </th>
                                        <th>
                                            Yeni Fiyat
                                        </th>
                                    </tr>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.tblSaha.adi)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.tblRezervasyonSaatleri.aciklama)
                                            </td>
                                            <td>
                                                @*@Html.DisplayFor(modelItem => item.fiyat) TL*@

                                                <h5 id="eskiFiyat_@item.fiyatId">@item.fiyat TL</h5>
                                            </td>
                                            <td>
                                                <div class="form-group">
                                                    <input type="number" placeholder="10 TL" name="txtYeniFiyat_@item.fiyatId" id="txtYeniFiyat_@item.fiyatId" />
                                                    <button type="submit" class="btn btn-default btn-sm" onclick="guncelle(@item.fiyatId)">Güncelle</button>
                                                </div>
                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>
                 

                        

    </div>

</div>

<script>
    $('#sahaselect').change(function () {
        var val1 = $('#sahaselect option:selected').val();
        $('#frmindex').submit();

    }); 
 
</script>


<script>
    function tumunuguncelle() {

        var adi = $("#sahaselect :selected").text();

        var id = $("#sahaselect :selected").val();

        var fiyat = $("#txtTumFiyat").val();

        swal({
            title: "Tüm Fiyatlar Güncellenecek!",
            text: adi+" isimli sahanın tüm saat fiyatları güncellenecek, işleme devam etmek istiyor musunuz?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Evet, güncelle!",
            closeOnConfirm: false
        },
        function () {
            $.ajax(
                {
                    type: "post",
                    url: "/yonetimpaneli/fiyattanimlama/TumunuGuncelle",
                    data: { saha: id, fiyat: fiyat },
                    success: function (data) {
                        if (data.basarili == true) {
                            swal({
                                title: "Harika!",
                                text: data.text,
                                type: "success",
                                showCancelButton: false,
                                confirmButtonColor: "#DD6B55",
                                confirmButtonText: "Tamam!",
                                closeOnConfirm: false
                            },
                            function () {
                                window.location = "/yonetimpaneli/fiyattanimlama";
                            });
                        }
                        else {
                            //alert(data.text);
                            swal("HATA", data.text, "error");
                        }
                    }
                }
                )

        });


    }
</script>













<script type="text/javascript">
    function guncelle(id) {
        
        var yeniFiyat= $("#txtYeniFiyat_" + id).val();
          
        //Posting them to server with ajax
        $.ajax({
            url: '/fiyattanimlama/fiyatguncelle',
            type: 'POST', 
            data:{ id:id, yeniFiyat:yeniFiyat },
            success: function (data) {
                if (data==true) {
                    //alert('Fiyat Güncellendi')
                    document.getElementById("eskiFiyat_" + id).innerHTML = yeniFiyat + " TL";
                    $("#txtYeniFiyat_" + id).val("");
                } 
            },
            error: function (hata, ajaxOptions, thrownError) {
                alert('hata'); 
            }
        });
    }
</script>